from __future__ import annotations

from pathlib import Path

DEMO_VERSION = "0.001-demo-jtxt"
SPEC_VERSION = "0.001"
SUPPORTED_CARRIERS = {"jpeg", "jpg", "txt"}
SUPPORTED_LAYOUTS = {"sparse", "sparse-with-chaff"}
DEFAULT_LAYOUT = "sparse-with-chaff"
DEFAULT_MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024
DEFAULT_MAX_STATES = 5
MIN_FRAGMENT_SIZE = 32
MAX_FRAGMENTS_PER_STATE = 8
JPEG_MAGIC = b"DATAMORPHO\x00JPEG\x00"
TXT_BEGIN_MARKER = "===DATAMORPHO-BEGIN==="
TXT_END_MARKER = "===DATAMORPHO-END==="
TXT_MANIFEST_BEGIN = "===DATAMORPHO-MANIFEST-BEGIN==="
TXT_MANIFEST_END = "===DATAMORPHO-MANIFEST-END==="
TXT_PAYLOAD_BEGIN = "===DATAMORPHO-PAYLOAD-BASE64-BEGIN==="
TXT_PAYLOAD_END = "===DATAMORPHO-PAYLOAD-BASE64-END==="
CHUNK_WRAP = 76
DEFAULT_OUT_DIR = Path(".")
SIMPLE_SUITE = "simple"
HARDENED_SUITE = "hardened"
SUPPORTED_SUITES = {SIMPLE_SUITE, HARDENED_SUITE}
SIMPLE_FRAGMENT_SUITES = (
    "AES-256-GCM",
    "AES-256-CTR+HMAC-SHA-256",
)
HARDENED_FRAGMENT_SUITES = (
    "RSA-OAEP-4096+AES-256-GCM",
    "RSA-OAEP-4096+AES-256-CTR+HMAC-SHA-256",
)
AES_KEY_SIZE_BYTES = 32
AES_GCM_IV_BYTES = 12
AES_CTR_COUNTER_BYTES = 16
HMAC_SHA256_KEY_SIZE_BYTES = 32
RSA_BITS = 4096